openapi: 3.0.3
info:
  title: CU detail
  version: '1.0'
servers:
  - url: 'https://portal-api.nodereal.io/v1'
paths:
  /{apiKey}/cu-detail:
    get:
      description: CU detail
      summary: CU detail
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
          required: true
      operationId: getCU
      responses:
          '200':
            description: Returns user CU detail.
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: '#/components/schemas/response'
                    - type: object
                      properties:
                        data:
                          $ref: '#/components/schemas/cudetail'
components:
  responses:
          '200':
            description: Returns user CU detail.
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: '#/components/schemas/response'
                    - type: object
                      properties:
                        data:
                          $ref: '#/components/schemas/cudetail'
  schemas:
    cudetail:
      type: object
      properties:
        autoscaling:
          type: boolean
        cups:
          type: integer
        plan:
          type: string
        remainingQuota:
          type: integer
        totalQuota:
         type: integer
        usage:
          type: integer
        network:
          type: string
    response:
      type: object
      properties:
        code:
          type: integer
        data: {}
        msg:
          type: string
